version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: library_postgres
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library_network

  app:
    build: .
    container_name: library_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: librarydb
      DB_SSLMODE: disable
    depends_on:
      - postgres
    networks:
      - library_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  library_network:
    driver: bridge